- 
  name: install-pkg
  hosts: right
  become: true
  vars:
    packages:
      - curl
      - nginx
  tasks: 
    - name: install curl + nginx
      become: true
      ansible.builtin.apt:
        pkg: "{{ item }}"
      with_items: "{{ packages }}"
      when: ansible_distribution == 'Ubuntu'